### ISSUE TITLE
Non-existent official-package-repositories.list

### ISSUE THREAD

**Issue by rafifos** [a7r3/scripts#11]
ScriBt throws this on the "Analyzing Distro" step (on "Install Build Dependencies")

"grep: /etc/apt/sources.list.d/official-package-repositories.list: File or directory not found"

- And also, it throws this on the install step "E: Couldn't find any package by glob 'libwxgtk2.8-dev'"

i'm using Zorin OS 12 (Based on Xenial), x64

**Comment by rafifos** [comment]
PS: one alternative for libwxgtk2.8-dev (since it was removed from official repositories) is to download it from ubuntu's launchpad

https://launchpad.net/ubuntu/xenial/amd64/libwxgtk2.8-dev/2.8.12.1+dfsg2-2ubuntu2

**Comment by a7r3** [comment]
Coincidentally, I experienced the same error on trying it on a random PC.
Looking for Alternatives...

**Comment by a7r3** [comment]
@Rahh1112 Can you provide the output of this command ?

```cat /etc/os-release```

For me being on Linux Mint 17.3, the output is..

```arvind@a7r3dev-Aspire-5734Z ~ $ cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```
And this output gives me a relevant result.

I'd search for more alternatives meanwhile...

**Comment by rafifos** [comment]
Here it is

> NAME="Zorin OS"
VERSION="12"
ID=Zorin OS
ID_LIKE=ubuntu
PRETTY_NAME="Zorin OS 12"
VERSION_ID="12"
HOME_URL="http://www.zorinos.com/"
SUPPORT_URL="http://www.zorinos.com/help"
BUG_REPORT_URL="https://bugs.launchpad.net/zorin-os/+filebug"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Comment by a7r3** [comment]
Hmm, I get the relevant information from your Output. But it is from a different variable. 

Thanks for reporting. I'd reply back with the usability of this on other Distributions.

**Comment by a7r3** [comment]
Already working on it. Hope it gets sorted.

**Comment by a7r3** [comment]
@Rahh1112 Workaround / Fix (hopefully) Implemented, would get it tested on different OSes

**Comment by rafifos** [comment]
I'm happy to see it fixed, but (for now..) i can't test the script anymore, i have to switch to windows.. i hate those visual studio projects of my tech class ç.ç

**Comment by a7r3** [comment]
Haha, no issues. Thanks for reporting it, didn't have much testers in other OSes when i added this long back.

Tag me if you've tested this, anytime.

**#HappyScriBting**
