### ISSUE TITLE
[FEATURE REQUEST] Export a custom ScriBt user and host in kernel build

### ISSUE THREAD

**Issue by rafifos** [a7r3/scripts#18]
The title explains all, exporting a user and host in kernel build (KBUILD_BUILD_USER, KBUILD_BUILD_HOST) will let the user knows that the kernel (and possibly the rom itself) was built with ScriBt

And add a optional feature to customize the user and host.

**Comment by a7r3** [comment]
Setting **Custom user@host** is okay for me, setting host=ScriBt or anything else should be up to the user

Would be added with v1.65, waiting for some free time :sleeping:

**Comment by a7r3** [comment]
Added it...

[https://github.com/a7r3/ScriBt/commit/1fa9167b1cf7863583d654b47ac227d3a578682e](Here)

![custuserhost](https://cloud.githubusercontent.com/assets/14874906/23257042/f9998112-f9e7-11e6-9261-3e5ee7318829.png)

**Comment by rafifos** [comment]
ohho this looks good xD

**Comment by a7r3** [comment]
Final, would be pushed soon

![screenshot from 2017-02-24 16-23-03](https://cloud.githubusercontent.com/assets/14874906/23301567/8f914254-fab0-11e6-9293-38c9dac263f3.png)

**Comment by a7r3** [comment]
Ok, ScriBt v1.67 pushed to `master` with this Feature included. Issue Solved
Thanks @h4ndshake  :+1:
