### ISSUE TITLE
[FEATURE REQUEST] Cleanup when exiting the program

### ISSUE THREAD

**Issue by timschumi** [a7r3/scripts#19]
It would be nice if ScriBt would delete the temp files that are created when it was run. Also, is there a way that there won't be a new upScriBt.sh when the program is run? It could be deleted automatically, too. But that would cause problems if you're currently inside the ScriBt folder

Thanks

**Comment by a7r3** [comment]
About `temp_*` files,
It was Initially made to be deleted that way, but some of the temp files, eg. temp_sync, and temp_compile, contain the logs of Syncing and Compiling respectively. So these files, along with other temp files are kept intact.

However, these files are removed and `touch` ed on the next run of ScriBt.

About upScriBt,
upScriBt is meant to be force-fetched, irrespective of git status. In case there's a major flaw with it, I'd just update upScriBt, and it'd be force-fetched to work properly.

And, I needed an opinion on this. I thought of...

* Creating a Seperate branch for upScriBt. By this, upScriBt would be cloned only on the start of ScriBt, and would get deleted If I add the required code to do so. At the same time, it's commit history could be seperately maintained.

(It's not possible to get the past commit history, just the future commits can be made on a seperate branch)

**Comment by timschumi** [comment]
I'll prepare some stuff and maybe open a PR on that :)
Also, if upScriBt is fetched from the server every time, shouldn't it be safe to delete it when the program ends?

**Comment by a7r3** [comment]
Yep, it is safe.

**Comment by timschumi** [comment]
I guess this can be closed now, as I opened PRs which fix the described things
