### ISSUE TITLE
[FEATURE DISCUSSION] Patch manager

### ISSUE THREAD

**Issue by timschumi** [a7r3/scripts#24]
For some devices the ROM's source needs to be patched before building to generate a bootable build. What about adding a patch manager which keeps track of patches which could be applied and which are already applied? I could put that into the program myself, but I wanted to know what you think of this before starting to work on it

**Comment by a7r3** [comment]
Patches like ?

**Comment by timschumi** [comment]
Patches like this:
https://github.com/SiniTurk/android_device_samsung_cs02/blob/cm-13.0/patch/patch.diff

For changes that are too "unstable" for other devices to get them merged (or even to stay inside the local repository), but are still needed for that specific device.

Btw, this is not a real future-request, as I will add that myself into the program if you think this would be useful

**Comment by akhilnarang** [comment]
Instead of patches tho, maybe keep a file "cherry-picks.txt" (which git will ignore). Can contain links of commit to be picked, script can parse the URL and get the path to pick in and SHA of commit to pick :D

**Comment by timschumi** [comment]
I prefer to use patches, as I don't need network access and I don't need to do a commit and update cherry-picks.txt every time I experiment with those changes.
I opened a PR (#25) on how I plan to have this implemented. It still needs at least a cleanup though
Also, I think it would be much more work to develop a format for the cherry-picks.txt file to match the repositories with the commit ids than just using simple patch files

**Comment by a7r3** [comment]
Oh, I just understood the purpose. :thinking: 
So, this is for patches which are to be applied to the Source Code, and which are present in the Device Tree, right ?

Is this convention followed by other Device trees ?

**Comment by timschumi** [comment]
Yes, that's correct.

I don't know any other devices (except those with samsung hawaii boards) which need patching atm. But all I have seen do have a diff file in a subfolder called "patch"

**Comment by timschumi** [comment]
Dear visitor. If you want to know about the development process of this feature, please visit this Pull Request: #25
