### ISSUE TITLE
[Nougat Building] Some fixes for minor unrelated issues

### ISSUE THREAD

**Issue by Caio99BR** [a7r3/scripts#27]
Can you add a workaround for Nougat builds under PC with less than 4GB?
I made these changes, I think if you have a option for it on your script it will be a good fallback (or warning) for old PC's:

> https://github.com/TeamVee-SS/android_.repo_local_manifests/commit/ceddb0db6c424f3b0c54f05d89b417586fa17475#diff-0b83f9dedf40d7356e5ca147a077acb4
> https://github.com/TeamVee-SS/android_.repo_local_manifests/commit/ceb4a3d98f49dd4aedec75b53f89544d9ced06ee

Also check it:

> https://android-review.googlesource.com/#/c/307208/

That's all, sorry for inconvenience and my English. Feel free to close this if you want.

**Comment by a7r3** [comment]
@Caio99BR From this Issue, what do you guys say about these Jacky boi Configs ?

**Comment by akhilnarang** [comment]
@Caio99BR Better to export the values each time? Instead of replacing in .jack-*

**Comment by Caio99BR** [comment]
I don't know, that is just a idea.

**Comment by a7r3** [comment]
#29 
@Caio99BR please move on to this PR, I've adapted the code

**Comment by Caio99BR** [comment]
Discussion moved to #29
